--- #YAML:1.0
name:               MARC-Record
version:            2.0.2
abstract:           Perl extension for handling MARC records
author:
    - Galen Charlton <gmcharlt@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:        0
    File::Find:  0
    File::Spec:  0
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
