---
abstract: 'Perl extension for handling MARC records'
author:
  - 'Galen Charlton <gmcharlt@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MARC-Record
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  File::Find: 0
  File::Spec: 0
  Test::More: 0
version: v2.0.5
