# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MARC-Record
version:      1.39_02
version_from: lib/MARC/Record.pm
installdirs:  site
requires:
    Carp:                          0
    File::Find:                    0
    File::Spec:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
