#!/usr/bin/perl -w

use warnings;
use strict;
use integer;

use MARC::Record;

warn "Using MARC::Record v$MARC::Record::VERSION\n";


my $marc = MARC::Record->new();

# Note that the length on the leader is bad.  No problem.

$marc->leader("00000nam  22002538a 4500");
my $nfields = $marc->add_fields(
	["001","fol05865967"],
	["003","IMchF"],
	["010", "","", 
		a => "   00055799",
		],
	[100, "1","",
		a => "Wall, Larry."
		],
	[245, "1","0",
		a => "Programming Perl / ",
		c => "Larry Wall, Tom Christiansen & Jon Orwant.",
		],
	[250, "", "",
		a => "3rd ed.",
		],
	[260, "", "",
		a => "Cambridge, Mass. : ",
		b => "O'Reilly, ",
		c => "2000.",
		],
	[650, " ","0",
		a => "Perl (Computer program language)",
		],
	[700, "1"," ",
		a => "Christiansen, Tom.",
		],
	[700, "1"," ",
		a => "Orwant, Jon.",
		],
	);

die "Error: $MARC::Record::ERROR" unless defined $nfields;

print $marc->as_usmarc;
